export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const WIDGET_CHANGE_CURRENT_PAGE = 'WIDGET_CHANGE_CURRENT_PAGE';
export const WIDGET_LIST_INFO_STORE = 'WIDGET_LIST_INFO_STORE';
export const WIDGET_LIST_SELECT = 'WIDGET_LIST_SELECT';
export const WIDGET_INFO_UPDATE = 'WIDGET_INFO_UPDATE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
