export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const WIDGET_INFO_REQUEST = 'WIDGET_INFO_REQUEST';
export const WIDGET_INFO_RESULT = 'WIDGET_INFO_RESULT';
export const WIDGET_LIST_INFO_STORE = 'WIDGET_LIST_INFO_STORE';