export const SETTING_CHANGE_CURRENT_PAGE = 'SETTING_CHANGE_CURRENT_PAGE';
export const SETTING_CHANGE_FILTER = 'SETTING_CHANGE_FILTER';
export const SETTING_SELECT_WIDGET = 'SETTING_SELECT_WIDGET';

// Preference ActionType
export const OPEN_PREFERENCE = 'OPEN_PREFERENCE';
export const CLOSE_PREFERENCE = 'CLOSE_PREFERENCE';

// Widget ActionType
export const ALLOCATE_ID_TARGET_WIDGET = 'ALLOCATE_ID_TARGET_WIDGET';
export const CLOSE_TARGET_WIDGET = 'CLOSE_TARGET_WIDGET';
export const DELETE_TARGET_WIDGET = 'DELETE_TARGET_WIDGET';
export const REGISTER_NEW_WIDGET = 'REGISTER_NEW_WIDGET';
export const REGISTER_NEW_WIDGET_BROWSER_WINDOW = 'REGISTER_NEW_WIDGET_BROWSER_WINDOW';
export const REGISTER_NEW_WIDGET_BROWSER_WINDOWS = 'REGISTER_NEW_WIDGET_BROWSER_WINDOWS';
export const SHOW_TARGET_WIDGET = 'SHOW_TARGET_WIDGET';
export const UPDATE_TARGET_WIDGET_INFO = 'UPDATE_TARGET_WIDGET_INFO';

// Temp Modal action
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
