export const SETTING_SELECT_WIDGET = 'SETTING_SELECT_WIDGET';

export const SET_INITIAL_STORE = 'SET_INITIAL_STORE';

// Preference ActionType
export const ALLOCATE_PREFERENCE_ID = 'ALLOCATE_PREFERENCE_ID';
export const OPEN_PREFERENCE = 'OPEN_PREFERENCE';
export const CLOSE_PREFERENCE = 'CLOSE_PREFERENCE';

// Widget ActionType
export const ALLOCATE_ID_TARGET_WIDGET = 'ALLOCATE_ID_TARGET_WIDGET';
export const CLOSE_TARGET_WIDGET = 'CLOSE_TARGET_WIDGET';
export const DELETE_TARGET_WIDGET = 'DELETE_TARGET_WIDGET';
export const REGISTER_NEW_WIDGET = 'REGISTER_NEW_WIDGET';
export const SHOW_TARGET_WIDGET = 'SHOW_TARGET_WIDGET';
export const UPDATE_TARGET_WIDGET_INFO = 'UPDATE_TARGET_WIDGET_INFO';
export const SET_ALL_WIDGET_ISOPEN_FALSE = 'SET_ALL_WIDGET_ISOPEN_FALSE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const OPEN_BROWSER_WINDOW = 'OPEN_BROWSER_WINDOW';
export const CLOSE_BROWSER_WINDOW = 'CLOSE_BROWSER_WINDOW';

export const SET_LANGUAGE_ENGLISH = 'SET_LANGUAGE_ENGLISH';
export const SET_LANGUAGE_KOREAN = 'SET_LANGUAGE_KOREAN';
export const TOGGLE_AUTO_LAUNCH = 'TOGGLE_AUTO_LAUNCH';
export const TOGGLE_AUTO_ACTIVE_WIDGET = 'TOGGLE_AUTO_ACTIVE_WIDGET';
export const TOGGLE_WIDGET_MODE = 'TOGGLE_WIDGET_MODE';
export const TRAY_WINDOW_OPEN = 'TRAY_WINDOW_OPEN';
export const TRAY_WINDOW_CLOSE = 'TRAY_WINDOW_CLOSE';

export const SEARCH_CHANGE_KEYWORD = 'SEARCH_CHANGE_KEYWORD';
export const SEARCH_SET_FILTER = 'SEARCH_SET_FILTER';
export const SEARCH_WIDGET_SELECT_INCREASE = 'SEARCH_WIDGET_SELECT_INCREASE';
export const SEARCH_WIDGET_SELECT_DECREASE = 'SEARCH_WIDGET_SELECT_DECREASE';
export const SEARCH_WINDOW_HIDE = 'SEARCH_WINDOW_HIDE';

export const UPDATE_CHECK_REQUEST = 'UPDATE_CHECK_REQUEST';
export const UPDATE_CHECK_SUCCESS = 'UPDATE_CHECK_SUCCESS';
export const UPDATE_CHECK_FAILURE = 'UPDATE_CHECK_FAILURE';
export const UPDATE_DOWNLOAD_REQUEST = 'UPDATE_DOWNLOAD_REQUEST';
export const UPDATE_DOWNLOAD_SUCCESS = 'UPDATE_DOWNLOAD_SUCCESS';
export const UPDATE_DOWNLOAD_FAILURE = 'UPDATE_DOWNLOAD_FAILURE';
export const UPDATE_DOWNLOAD_PROGRESS = 'UPDATE_DOWNLOAD_PROGRESS';
export const UPDATE_SKIP_THIS_VERSION = 'UPDATE_SKIP_THIS_VERSION';
export const UPDATE_SET_AUTO_CHECK_UPDATE = 'UPDATE_SET_AUTO_CHECK_UPDATE';
export const UPDATE_SET_AUTO_UPDATE = 'UPDATE_SET_AUTO_UPDATE';
export const UPDATE_SET_NOT_AUTO = 'UPDATE_SET_NOT_AUTO';
export const UPDATE_PROGRESS_WINDOW_OPEN = 'UPDATE_PROGRESS_WINDOW_OPEN';
export const UPDATE_PROGRESS_WINDOW_CLOSE = 'UPDATE_PROGRESS_WINDOW_CLOSE';
export const UPDATE_PROGRESS_CANCEL = 'UPDATE_PROGRESS_CANCEL';
export const UPDATE_INSTALLING_DOWNLOADED = 'UPDATE_INSTALLING_DOWNLOADED';
