export const STATUS_OPEN_PREFERENCE = 'STATUS_OPEN_PREFERENCE';
export const STATUS_CLOSE_PREFERENCE = 'STATUS_CLOSE_PREFERENCE';
export const STATUS_OPEN_WIDGET = 'STATUS_OPEN_WIDGET';
export const STATUS_CLOSE_WIDGET = 'STATUS_CLOSE_WIDGET';

export const SETTING_CHANGE_CURRENT_PAGE = 'SETTING_CHANGE_CURRENT_PAGE';
export const SETTING_CHANGE_FILTER = 'SETTING_CHANGE_FILTER';
export const SETTING_SELECT_WIDGET = 'SETTING_SELECT_WIDGET';

export const WIDGETS_REGISTER_NEW = 'WIDGETS_REGISTER_NEW';
export const WIDGETS_OPEN_WINDOW = 'WIDGETS_OPEN_WINDOW';
export const WIDGETS_CLOSE_WINDOW = 'WIDGETS_CLOSE_WINDOW';
export const WIDGETS_DELETE = 'WIDGETS_DELETE';

// Information ActionType
export const STORE_CURRENT_INFORMATION = 'STORE_CURRENT_INFORMATION';
export const LOAD_STORED_INFORMATION = 'LOAD_STORED_INFORMATION';

// Widget ActionType
export const CLOSE_TARGET_WIDGET = 'CLOSE_TARGET_WIDGET';
export const DELETE_TARGET_WIDGET = 'DELETE_TARGET_WIDGET';
export const REGISTER_NEW_WIDGET = 'REGISTER_NEW_WIDGET';
export const REGISTER_NEW_WIDGET_BROWSER_WINDOW = 'REGISTER_NEW_WIDGET_BROWSER_WINDOW';
export const SHOW_TARGET_WIDGET = 'SHOW_TARGET_WIDGET';
export const UPDATE_TARGET_WIDGET_INFO = 'UPDATE_TARGET_WIDGET_INFO';
