export const WIDGET_SHOW_INACTIVE = 'WIDGET_SHOW_INACTIVE';
export const WIDGET_INFO_REQUEST = 'WIDGET_INFO_REQUEST';
export const WIDGET_INFO_RESULT = 'WIDGET_INFO_RESULT';
export const WIDGET_MANAGE = 'WIDGET_MANAGE';
export const WIDGET_OPEN = 'WIDGET_OPEN';
